### ISSUE TITLE
WxWidgets 3.2.3 released

### ISSUE THREAD

**Issue by neoxeo** [alternetsoft/AlternetUI#54]
@generalloki,

I don't know impact but I think it would be interesting to try an update with this release 3.2.3.

Other point, .NET8.0 first official release will be available soon. I have try RC1 with windows and Linux. All seems to be ok : scripts, compile, tests.

With these two components, AlternetUI will be up to date.

**Comment by generalloki** [comment]
@neoxeo, This is great to have new wxWidgets version. It's better to wait about 1-2 month as they can release something like 3.2.31 like it was previously. Also yesterday we have released new build, so wxWidgets update (and also webView update) will be done in the next build. As to net8, I beleive we will fully support it after it's release. It has no sense to use beta.

**Comment by generalloki** [comment]
In 0.9.405

- Updated webview to 2.1.0.2045.28.
- Updated wxWidgets to 3.2.3.

So I am closing this issue.

**Comment by neoxeo** [comment]
@generalloki 

Thanks a lot for this update.

If you have an old version installed of webview and wxWidgets, version 3.2.3 is not downloaded by install.bat or install.sh.

It would be a good thing to control version of wxWidgets. You can use "version-script.in" file to check this and download automatically the good version of wxWidgets it is not up-to-date.

**Comment by neoxeo** [comment]
@generalloki 

I have a warning message when I use install.sh : 
![Capture d’écran du 2023-10-29 09-25-43](https://github.com/alternetsoft/AlternetUI/assets/5283778/5edfae95-3280-40a3-80c0-80b8c6ad4604)

I don't remember if I have it before and if I have it with Windows

**Comment by generalloki** [comment]
@neoxeo 👍 Many thanks for the report!

- Webkit warning: I have seen this. You can run Install.Scripts\Ubuntu.Install.Packages.sh 
in order to install required packages (including webkit2gtk-4.1) and this warning will not be shown.

- In order to download latest version, just delete \External\WxWidgets\ folder
and latest supported wxWidgets will be installed when Install.sh or Install.bat is runned.
I doubt we will change anything related to the installation in the near future as there are many
more imported issues to fix/improve.
